name: Build and push docker image to dockerhub
on: push
jobs:
  push_to_repository: Push Docker image to dockerhub
  runs-on: ubuntu-latest
  steps:
    - name: checkout my rep code
      uses: actions/checkout@v3

    - name: Login into Dockerhub
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:mysubdir"
        push: true
        tags: user/app:latest